---
title: "Data Visualisations"
author: "Sarah Marshall"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(readr)
library(leaflet)
library(tidytext)
library(wordcloud)

#install.packages("wordcloud")
library(wordcloud)
#install.packages("RColorBrewer")
library(RColorBrewer)
```

```{r}
# Read in survey data
survey_data <- read_csv("data/Data Vis Survey Sample 2.csv")

# Read in schools data
directory <- read_csv("data/directory.csv",     skip = 15)

```

```{r}
# Clean schools data
directory_brief <- directory %>% 
  select(`School Name`, Longitude, Latitude, `Postal Code`) %>%
  mutate(SchoolName_clean = str_to_lower(`School Name`)) %>%
  drop_na()


# Merge survey and school data
survey_data_geo <- survey_data %>% 
  mutate(SchoolName_clean = str_to_lower(`School Name (full name)`)) %>% 
  left_join(directory_brief)  


```


# Where are you from?
```{r, fig.height=7, fig.width = 7}
schools <- leaflet()%>% 
  setView(lng = mean(survey_data_geo$Longitude), 
          lat = mean(survey_data_geo$Latitude), zoom = 5) %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addCircleMarkers(lng=survey_data_geo$Longitude, lat=survey_data_geo$Latitude, popup=survey_data_geo$SchoolName_clean)

schools

```

```{r, include = FALSE}
# Identify schools not plotted
survey_data_geo %>% filter(is.na(Longitude) | is.na(Latitude))

```

```{r}

mysize = 16
#survey_data %>% names()

survey_data %>% ggplot() + 
  geom_bar(mapping = aes(x = `Subject Area Taught`) )+ 
  theme(text=element_text(size=mysize))+ 
  labs(title = "What do you teach?")
```

 
```{r}
survey_data %>% ggplot() + 
  geom_bar(mapping = aes(x = `Do you prefer cats or dogs?`))+ 
  labs( x = "Animal", title  = "Do you prefer cats or dogs?")+ theme(text=element_text(size=mysize))


```

```{r}
survey_data %>% ggplot() + 
  geom_bar(mapping = aes(x = `How long did it take you to get here this morning?`))+ 
  labs( x = "Minutes", title  = "Travel time this morning")+ theme(text=element_text(size=mysize))

```


```{r}

survey_data %>% ggplot() + 
  geom_histogram(mapping = 
                   aes(x = `How long did it take you to get here this morning, in minutes?`), 
                 binwidth = 10) + 
  labs( x = "Minutes", title  = "Travel time this morning")+ theme(text=element_text(size=mysize))

```

```{r}
year_levels_taught = tibble(years = 
  survey_data$`What year levels do you teach? Select all that apply.`  %>% 
    str_split(pattern = ";") %>% unlist())%>% drop_na()



year_levels_taught %>% ggplot() + 
  geom_bar(mapping = aes(x = years)) + 
  labs(x = "Year Level", title = "What year levels do you teach?")+
  theme(text=element_text(size=mysize))



```

# What do you hope to get out of this workshop?
```{r}
# data prep
#Create a vector containing only the text
text_df <- survey_data %>% 
  select(`What do you hope to get out of this workshop?`) %>% 
  rename(text = `What do you hope to get out of this workshop?`
)


text_df %>%
  unnest_tokens(output = word, #new column name
                input = text #column name in df
  ) %>%
  anti_join(stop_words) -> text_tidy 

```

```{r}

pal <- brewer.pal(9,"BuGn")
pal <- pal[-(1:4)] #remove light colours
  
text_tidy  %>%
count(word) %>%
  with(wordcloud(word, n, max.words = 100, colors = pal,
                 rot.per = 0, fixed.asp = FALSE))



```


